INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Super Secão Max', 88.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/Tapete.jpg', 'Para cães de todas as idades, abas laterais com vedacão total, extra gel e emb. 30 unidades.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Ração Golden filhote', 57.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/racao.jpg', 'Indicada para cães filhotes, auxilia no equilíbrio intestinal, pacote 15kg.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Brinquedo Pelúcia', 27.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/pelucia.jpg', 'Indicado para cães, divertido e criativo, ajuda a combater o estresse.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Cama PETZ', 179.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/cama.jpg', 'Super macia, dupla face, firme e resistente e não absorve umidade.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Moleton com capuz', 109.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/moleton.jpg', 'Ideal para o inverno, vai deixar o seu cão aquecido e estiloso.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Banho e Tosa', 145.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/banho_tosa.jpg', 'Seu pet limpinho, banho com hidratação e corte com tesoura.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Casa Plástica', 699.0, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/casa.jpg', 'Pode ficar em área externa, fácil de limpar e montagem rápida.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Anti pulgas/carrapatos', 281.9, 'https://raw.githubusercontent.com/flaviaschuenquer/fsdelivery/main/assets/remedio.jpg', 'Elimina pulgas e carrapatos rapidamente e não sai com o banho.');

INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T10:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -22.946779, -43.217753, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T15:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -25.439787, -49.237759, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T16:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T12:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T08:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T14:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T09:00:00Z');

INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 8);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 3);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 7);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 5);
